# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

webicks_muttery:
    resource: "@WebicksMutteryBundle/Controller/"
    type:     annotation
    prefix:   /
    
_assetic:
    resource: .
    type:     assetic