services:
    facebook.user:
        class: Webicks\MutteryBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            cache:    "@cache"
            container: "@service_container"