services:
    facebook.user:
        class: Webicks\MutteryBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
    
    youtube:
        class: Webicks\MutteryBundle\Service\YouTube\YouTube
        arguments:
            session: "@session"
            router: "@router"
            developerKey: "%youtube.developerKey%"
    chat:
        class: Webicks\MutteryBundle\Service\Chat\ChatAdmin
        arguments:
            session: "@session"
            router: "@router"        