<?php

namespace Webicks\MutteryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MutterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MutterRepository extends EntityRepository
{
}
