<?php

namespace Webicks\MutteryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MutterDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MutterDataRepository extends EntityRepository
{
}
